CREATE TABLE `preguntas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pregunta` text NOT NULL,
  `respuesta` text NOT NULL,
  `keywords` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `preguntas` (`id`, `pregunta`, `respuesta`, `keywords`) VALUES
(1, '¿Cuáles son los requisitos para las prácticas pre profesionales?', 'Para participar en las Prácticas Pre Profesionales, necesitas haber aprobado al menos 160 créditos y estar en los planes de estudios 2013, 2016, o 2020 de la Escuela Profesional de Ingeniería de Sistemas. Estos requisitos aseguran que tengas la formación necesaria para aprovechar al máximo la experiencia.', 'requisitos, prácticas pre profesionales, créditos, plan de estudios, requisitos prácticas, requisitos pre profesionales, formación necesaria'),
(2, '¿Cómo solicito la carta de presentación?', 'Para solicitar la Carta de Presentación, debes utilizar la Mesa de Partes Virtual. Necesitarás adjuntar el nombre de la empresa, el representante de la empresa, el voucher de pago por concepto de servicios administrativos, y tu histórico de notas. Asegúrate de tener toda la documentación completa para procesar tu solicitud de manera eficiente.', 'solicitar, carta de , mesa de partes virtual, documentación, proceso de solicitud, carta presentación solicitud'),
(3, '¿Qué documentos necesito para el reconocimiento de prácticas?', 'Para obtener el reconocimiento de tus prácticas, debes presentar el recibo de pago (código C11060031), el informe final de tus actividades, y la carta de presentación emitida por la empresa donde realizaste las prácticas. Estos documentos permiten validar tu experiencia y formalizar el reconocimiento.', 'documentos, reconocimiento de prácticas, recibo de pago, informe final, carta de presentación, requisitos reconocimiento, validación'),
(4, '¿Dónde puedo encontrar más información sobre las prácticas?', 'Puedes encontrar información adicional en el sitio web oficial de la universidad a través del siguiente enlace: <a href=\"https://sites.google.com/view/pppsistemasuac/inicio?authuser=0\" target=\"_blank\">Sitio oficial de la UAC</a>. Aquí encontrarás detalles actualizados sobre los requisitos y procesos para las prácticas.', 'información, sitio web, universidad, UAC, prácticas, más información, sitio prácticas, detalles actualizados'),
(5, '¿Cuántos créditos necesito para iniciar las prácticas pre profesionales?', 'Para iniciar las Prácticas Pre Profesionales, debes contar con al menos 160 créditos aprobados. Este requisito asegura que tengas el conocimiento necesario para aprovechar tu experiencia en el entorno profesional.', 'créditos, mínimo, requisitos, iniciar prácticas, PPP, requisitos créditos, conocimiento necesario'),
(6, '¿Puedo iniciar mis prácticas pre profesionales sin tener la carta de presentación?', 'No, las Prácticas Pre Profesionales solo serán reconocidas a partir de la fecha de emisión de la carta de presentación o desde una fecha posterior. La carta de presentación es un documento esencial para formalizar tu participación en las prácticas.', 'iniciar, prácticas pre profesionales, carta de presentación, reconocimiento, requisitos, carta presentación requerida, formalización'),
(7, '¿Cómo puedo unirme al grupo de WhatsApp?', 'Para unirte al grupo de WhatsApp, sigue este enlace: <a href=\"https://chat.whatsapp.com/EQEBN6eAhOc6W3CVKULsed\" target=\"_blank\">Unirme al grupo de WhatsApp</a>. En el grupo podrás recibir actualizaciones y comunicados importantes relacionados con las prácticas.', 'unirse, grupo WhatsApp, enlace, chat, WhatsApp, grupo práctica, actualizaciones'),
(8, '¿Cuál es el horario de atención para ING 413?', 'El horario de atención para el curso ING 413 es: Lunes y Martes de 2:00pm a 4:00pm, y Jueves y Viernes de 7:00am a 9:00am. Asegúrate de asistir durante estos horarios para resolver tus dudas y recibir la asistencia necesaria.', 'horario, atención, ING 413, curso, horario de atención, horarios de clase, asistencia'),
(9, '¿Quién es el encargado de la coordinación del EPP?', 'El encargado de la coordinación del Ejercicio Pre Profesional es el Mtro. Ing. Nick Eugeny Pumasupa Paro, docente del DAIS - UAC. Puedes contactarlo a través del correo npumasupa@uandina.edu.pe o al celular +51 984 356 623 para cualquier consulta relacionada con el EPP.', 'coordinación, encargado, Mtro. Ing. Nick Eugeny Pumasupa Paro, contacto, correo, celular, coordinación EPP, consulta'),
(10, '¿Qué pasos debo seguir para obtener la carta de presentación?', 'Para obtener la carta de presentación, sigue estos pasos: 1. Realiza el pago por servicio académico. 2. Solicita la carta de presentación en la Mesa de Partes Virtual. 3. Completa los datos requeridos. 4. Adjunta los documentos necesarios. 5. Recibe la carta en tu correo institucional. Cada paso es crucial para asegurar una solicitud exitosa.', 'pasos, carta de presentación, proceso, requisitos, documentación, obtener carta, solicitud exitosa'),
(11, '¿Qué hacer si no recibo la carta de presentación?', 'Si no recibes la carta de presentación en un tiempo razonable, te recomendamos contactar al decanato de tu facultad o enviar un correo a npumasupa@uandina.edu.pe para verificar el estado de tu solicitud y resolver cualquier problema.', 'no recibir, carta de presentación, seguimiento, decanato, contacto, carta no recibida, verificación'),
(12, '¿Dónde encuentro los formatos para el informe final y el plan de PPP?', 'Los formatos para el informe final y el plan de PPP están disponibles en el siguiente enlace: <a href=\"https://sites.google.com/view/pppsistemasuac/formatos?authuser=0\" target=\"_blank\">Formatos de PPP</a>. Aquí podrás descargar los documentos necesarios para completar tu reporte y planificación.', 'formatos, informe final, plan de PPP, documentos, descarga, formatos disponibles, reportes'),
(13, '¿Qué beneficios ofrece el programa de prácticas pre profesionales?', 'El programa de prácticas pre profesionales ofrece varios beneficios, como la oportunidad de adquirir experiencia laboral en tu campo de estudio, mejorar tu currículum vitae, y aplicar los conocimientos teóricos en un entorno profesional. Además, te ayuda a desarrollar habilidades prácticas que son valiosas para tu futura carrera.', 'beneficios, programa, prácticas pre profesionales, experiencia laboral, oportunidades, mejora CV, habilidades prácticas'),
(14, '¿Cómo se evalúan las prácticas pre profesionales?', 'Las prácticas pre profesionales se evalúan mediante la presentación de un informe final, que será revisado junto con la carta de presentación y el recibo de pago. Este proceso asegura que tu experiencia y desempeño sean debidamente reconocidos y validados.', 'evaluación, prácticas pre profesionales, informe final, reconocimiento, evaluación de prácticas, proceso de evaluación'),
(15, '¿Cuál es la duración mínima para las prácticas pre profesionales?', 'La duración mínima para las prácticas pre profesionales es de 8 semanas. Durante este período, debes cumplir con el número de horas establecido por el programa para completar tus prácticas de manera satisfactoria.', 'duración, prácticas pre profesionales, mínimo, semanas, horas requeridas, duración mínima'),
(16, '¿Puedo realizar mis prácticas en una empresa fuera de mi especialidad?', 'No, las prácticas pre profesionales deben realizarse en una empresa o institución relacionada con tu campo de estudio para garantizar que adquieras experiencia relevante y útil para tu formación académica.', 'prácticas pre profesionales, especialidad, empresa, campo de estudio, relevancia, experiencia relevante'),
(17, '¿Qué hacer si el chatbot no entiende mi pregunta?', 'Si el chatbot no entiende tu pregunta, intenta reformularla usando palabras clave relacionadas con el tema de las prácticas pre profesionales. Asegúrate de ser claro y específico en tu consulta para obtener una respuesta más precisa.', 'chatbot, no entiende, pregunta, reformular, palabras clave, claridad, consulta'),
(18, '¿Cómo puedo interactuar mejor con el chatbot?', 'Para interactuar mejor con el chatbot, formula preguntas claras y concisas. Usa palabras clave relacionadas con tu consulta y evita frases ambiguas. Si el chatbot no entiende tu pregunta, intenta ser más específico o simplificar tu consulta.', 'interactuar, chatbot, preguntas claras, palabras clave, frases ambiguas, especificidad'),
(19, '¿Hola?', '¡Hola! Soy ChatGPT, tu asistente para temas de prácticas pre profesionales. ¿En qué puedo ayudarte hoy?', 'hola, saludo, asistente, prácticas pre profesionales'),
(20, '¿hola?', '¡Hola! Estoy aquí para ayudarte con cualquier pregunta relacionada con las prácticas pre profesionales. ¿Qué necesitas saber?', 'hola, saludo, asistente, prácticas pre profesionales'),
(21, '¿Gracias?', '¡De nada! Si tienes más preguntas sobre prácticas pre profesionales, no dudes en preguntar. ¡Que tengas un buen día!', 'gracias, despedida, prácticas pre profesionales, agradecimiento'),
(22, '¿Adiós?', '¡Adiós! Si necesitas ayuda en el futuro con prácticas pre profesionales, aquí estaré para asistirte. ¡Cuídate!', 'adiós, despedida, prácticas pre profesionales, hasta luego'),
(23, '¿Cómo puedo contactar al encargado de la coordinación del EPP?', 'Puedes contactar al Mtro. Ing. Nick Eugeny Pumasupa Paro, encargado de la coordinación del Ejercicio Pre Profesional (EPP), a través del correo electrónico npumasupa@uandina.edu.pe o al número de celular +51 984 356 623. No dudes en comunicarte con él para resolver cualquier duda o consulta sobre el EPP.', 'contacto, encargado, EPP, correo, celular, Nick Eugeny Pumasupa, asistencia');



